# Generated by Django 2.0.6 on 2018-07-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
